version: '3.8'

services:
  coffeebaseapi:
    container_name: coffeebaseapi
    build:
      context: ./
    image: coffeebaseapi
    ports:
      - "8080:80"
    environment:
      spring.datasource.url: jdbc:mysql://host.docker.internal:3306/coffeebase_db
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
      clientId: ${GOOGLE_API_CLIENT_ID}
      fileService: local
    env_file:
      - .env
