version: '3.8'

services:
  coffeebaseapi:
    container_name: coffeebaseapi
    build:
      context: ./
    image: coffeebaseapi
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/coffeebase_db
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
      clientId: ${CLIENT_ID}
      fileService: local
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - custom

  mysql:
    image: mysql:latest
    container_name: coffeebase_mysql
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: coffeebase_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_coffeebase_data:/var/lib/mysql
    networks:
      - custom

volumes:
  mysql_coffeebase_data:
    
networks:
  custom:
    name: dupa
    external: false
    driver: bridge
