services:
  coffeebaseapi:
    container_name: coffeebaseapi
    build:
      context: ./
    image: coffeebaseapi
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/coffeebase_db
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
      clientId: ${CLIENT_ID}
      fileService: local
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - custom

  mysql:
    image: mysql:latest
    container_name: coffeebase_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: coffeebase_db
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DB_USER --password=$$DB_PASSWORD
      timeout: 10s
      retries: 20
    volumes:
      - mysql_coffeebase_data:/var/lib/mysql
    networks:
      - custom

volumes:
  mysql_coffeebase_data:
    
networks:
  custom:
    name: custom_network
    external: false
    driver: bridge
