spring:
  cloud:
    gcp:
      logging:
        enabled: true
      sql:
        instance-connection-name: coffeebase-379621:europe-central2:coffeebase-db
        database-name: coffeebase-db
  datasource:
    username: ${dbUser}
    password: ${dbPass}
