spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: ${sm://dbUser}
    password: ${sm://dbPassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    appId: coffeebase-379621
    gcp:
      logging:
        enabled: true
      sql:
        instance-connection-name: coffeebase-379621:europe-central2:coffeebase-db
        database-name: coffeebase_db

clientId: ${sm://clientId}
