spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: 'jdbc:mysql://localhost:3307/coffeebase_db'
    username: ${sm://dbUser}
    password: 'password'

clientId: ${clientId}
fileService: local
