spring:
  main:
    banner-mode: off
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
gcp:
  bucket:
    name: 'coffeebase-file-storage'
