spring:
  h2:
    console:
      enabled: true
      path: '/console'
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:h2:file:./CoffeeBase-testdb'
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: Coffeebase
  resource: coffeebase-client
  public-client: true