spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: 'jdbc:mysql://localhost:3306/coffeebase_db'
    username: 'user'
    password: 'password'

clientId: ${clientId}
