runtime: java
env: flex
runtime_config:
  operating_system: "ubuntu18"
  runtime_version: "11"
env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
  clientId: clientId=197200968254-uftl0ec1vual1ikvru1qtk2rialvbcji.apps.googleusercontent.com
  secret: secret=juIk650UdCxZwE4
handlers:
  - url: /.*
    script: this field is required but ignored
manual_scaling:
  instances: 1

