runtime: java17
env: standard
instance_class: F4
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"
env_variables:
  SPRING_PROFILES_ACTIVE: prod
handlers:
  - url: /.*
    script: this field is required but ignored

